### PR TITLE
arb: fix conflict with flint from homebrew-core

### PR DESCRIPTION
**Pull request by mwageringel**
This solves https://trac.sagemath.org/ticket/29104#comment:36.

### CODE REVIEW

**Comment by mwageringel** [comment]
@dimpase

**Comment by dimpase** [comment]
Thanks!

**Comment by dimpase** [comment]
By the way, shouldn't flint get `--disable-tls` option, just as arb does?

**Comment by mwageringel** [comment]
I do not know about that, sorry.

**Pull request merged**
